### ISSUE TITLE
Data tranzakcji - użyte zostało Settle Date zamiast Trade Date

### ISSUE THREAD

**Issue by Machoney** [divident/pitkalkulator#2]
Jak w temacie. 
Porównując ze swoimi obliczeniami zauważyłem, że datą tranzakcji w kalkulatorze to nie jest "Trade Date" z formularza, lecz "Settle Date". Może to powodować błędy przy wyliczaniu zysku/strat w związku z różnicą kursu dolara w NBP z D-1.

**Comment by divident** [comment]
_Settle date_ jest datą w której następuje właściwy zakup akcji czyli stajesz się posiadaczem akcja w tym dniu, a co do _trade date_ to tylko oznacza moment wrzucenia oferty kupna/sprzedaży na giełdę, ale transakcja nie musi się odbyć tego dnia. Przykładowo wystawiasz akcję APL na sprzedaż w poniedziałek, a ktoś kupi dopiero we wtorek, wtedy trade date będzie poniedziałek, a settle date wtorek i we wtorek następuje transfer gotówki dopiero.

**Comment by Machoney** [comment]
Okej, rozumiem. Dzięki.

**Comment by dawidchyrzynski** [comment]
@divident Nie do końca zgodzę się z tym tłumaczeniem i @Machoney słusznie zauważył, że przeliczanie kursu na podstawie settle date może być błędne. W momencie zakupu/sprzedaży papierów wartościowych (tj. trade date) dokonywany jest foreign exchange spot po ustalonej cenie z danego dnia. Settle date to tylko data zmiany właściciela papieru wartościowego, po cenie, która była uzgodniona podczas składania zamówienia (które jest zazwyczaj realizowane natychmiastowo).

Załóżmy, że kurs walut jest bardzo zmienny i dokonujemy zakupu akcji w dniu X po kursie 3.80zł za $1. Jeżeli dwa dni później kurs wynosi 4zł wówczas wartość zlecenia byłaby o wiele wyższa, ale my i tak płacimy kwotę, która była ustalona w dniu X.

**Comment by dawidchyrzynski** [comment]
Odnosząc się do Twojego stwierdzenia `ale transakcja nie musi się odbyć tego dnia`. Zgadza się, jeżeli zlecenie byłoby zrealizowane następnego dnia wówczas trade date byłby dniem realizacji, a nie złożenia. Zlecenia oczekujące nie są uwzględniane w raporcie (bo jaki by to miało sens?).

**Comment by Machoney** [comment]
@dawidchyrzynski rozmawiałem też z kalkulatorgieldowy.pl i oni wysłali zapytanie do US i _Settle Date_ powinno być brane pod uwagę przy wyliczaniu kursu. 

Niestety wahania kursu walutowego są w tym przypadku na naszą niekorzyść.
